### ISSUE TITLE
Email issue

### ISSUE THREAD

**Issue by Mehonoshin** [howtohireme/give-me-poc#264]
https://rollbar.com/howtohireme/givemepoc.org/items/25/occurrences/45286536112/
Not sure what happened. Maybe some network issue.

**Comment by reabiliti** [comment]
as an option, there may still be problems with setting up account security
example:
https://toster.ru/q/139273
https://stackoverflow.com/questions/18124878/netsmtpauthenticationerror-when-sending-email-from-rails-app-on-staging-envir
but, since the problem did not recur anymore, it's hard to know the reason.

**Comment by Mehonoshin** [comment]
Let close it for new then. We'll investigate it deeper, if it happens again.
